---
- hosts: kube_server
  user: ubuntu
  become: yes
  gather_facts: yes


  tasks:
    - name: Add a repository
      kubernetes.core.helm_repository:
         name: longhorn
         repo_url: https://charts.longhorn.io

    - name: Update the Helm Repo
      command:  helm repo update
 
    - name: Install Longhorn Chart
      kubernetes.core.helm:
        name: longhorn
        namespace: longhorn-system
        chart_ref: longhorn/longhorn
        create_namespace: yes
        values:
          defaultSettings:
            defaultReplicaCount: 1
          persistence:
            defaultClassReplicaCount: 1

    - name: Change the svc to NodePort
      command: kubectl patch svc longhorn-frontend -n longhorn-system --type='json' -p '[{"op":"replace","path":"/spec/type","value":"NodePort"},{"op":"replace","path":"/spec/ports/0/nodePort","value":32528}]'
